FROM jekyll/jekyll:3.8
# RUN deluser jekyll
# RUN groupadd -r -g 2000 trydirect; useradd -r -u 2000 -g 2000 -m -c "app account" -d /home/trydirect -s /bin/bash trydirect
# RUN chown -R trydirect. /srv/jekyll
WORKDIR /srv/jekyll
